# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Sender',
        ),
    ]
