# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 11:25
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20150712_1730'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='assigns_a_task_to_me',
            new_name='assigns_task_to_me',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='changes_a_task_from_a_shared_list_that_I_assigned_to_him_her',
            new_name='changes_task_from_shared_list_that_I_assigned_to_him_her',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='changes_a_task_from_a_shared_list_that_is_assigned_to_me',
            new_name='changes_task_from_shared_list_that_is_assigned_to_me',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='completes_a_task_from_a_shared_list',
            new_name='completes_task_from_shared_list',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='deletes_a_list_shared_with_me',
            new_name='deletes_list_shared_with_me',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='leaves_a_shared_list',
            new_name='leaves_shared_list',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='removes_me_from_a_shared_list',
            new_name='removes_me_from_shared_list',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='shares_a_list_with_me',
            new_name='shares_list_with_me',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='site_media/images/default_images/default_avatar_user.png', upload_to=users.models.get_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='order_tasks_dashboard',
            field=models.CharField(choices=[('Today->Overdue->You can do this too', 'Today->Overdue->You can do this too'), ('Overdue->Today->You can do this too', 'Overdue->Today->You can do this too')], default='Today->Overdue->You can do this too', max_length=40),
        ),
    ]
