# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20161029_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='changes_task_from_shared_list_that_I_assigned_to_him_her',
            new_name='changes_task_from_shared_list_that_i_assigned_to_him_her',
        ),
    ]
