# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20170530_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dialog_time_when_task_finished_in_project',
            field=models.BooleanField(default=False),
        ),
    ]
