# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 21:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_dialog_time_when_task_finished_in_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
