# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20171211_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='future_tasks_sort_by',
            field=models.CharField(choices=[('finishDate, finishTime, name', 'finishDate, finishTime, name'), ('-finishDate, finishTime, name', '-finishDate, finishTime, name')], default='finishDate, finishTime, name', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='overdue_tasks_sort_by',
            field=models.CharField(choices=[('priority, finishDate, name', 'priority, finishDate, name'), ('priority, -finishDate, name', 'priority, -finishDate, name')], default='priority, finishDate, name', max_length=40),
        ),
    ]
