# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180225_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='future_tasks_sort_by',
            field=models.CharField(choices=[('finishDate finishTime name', 'finishDate, finishTime, name'), ('-finishDate finishTime name', '-finishDate, finishTime, name')], default='finishDate finishTime name', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='overdue_tasks_sort_by',
            field=models.CharField(choices=[('priority finishDate name', 'priority, finishDate, name'), ('priority -finishDate name', 'priority, -finishDate, name')], default='priority finishDate name', max_length=40),
        ),
    ]
