# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20180320_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='all_tasks_view',
            field=models.CharField(choices=[('extended', 'extended'), ('simple', 'simple')], default='simple', max_length=40),
        ),
    ]
