# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20180601_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='order_tasks_dashboard',
            field=models.CharField(choices=[('Today->Overdue', 'Today->Overdue'), ('Overdue->Today', 'Overdue->Today')], default='Today->Overdue', max_length=40),
        ),
    ]
