# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 21:40
from __future__ import unicode_literals

from django.db import migrations

def  change_default_order_tasks(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
            user.order_tasks_dashboard = "Overdue->Today"
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20181009_2340'),
    ]

    operations = [
        migrations.RunPython(change_default_order_tasks),
    ]
