# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20171211_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
