# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20180516_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type_finish_date',
            field=models.IntegerField(blank=True, choices=[[0, 'by'], [1, 'on']], default=1, null=True),
        ),
    ]
