# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 21:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_errors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logerror',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
