# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 23:53
from __future__ import unicode_literals

import dashboard.lists.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20150207_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='color',
            field=models.CharField(default='#2c86ff', max_length=100),
        ),
        migrations.AlterField(
            model_name='list',
            name='default_finish_date',
            field=models.IntegerField(blank=True, choices=[[0, 'today'], [1, 'tomorrow'], [2, 'next week']], null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='default_priority',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.TextField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='logo',
            field=models.ImageField(default='images/default_images/default_list_logo.png', upload_to=dashboard.lists.models.get_path),
        ),
        migrations.AlterField(
            model_name='list',
            name='share_with',
            field=models.ManyToManyField(blank=True, related_name='share_with', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharelistpending',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
