# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_list_defaulttaskview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='defaultTaskView',
            new_name='default_task_view',
        ),
    ]
