# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_auto_20171211_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='dialog_time_when_task_finished',
            field=models.BooleanField(default=False),
        ),
    ]
