# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_list_dialog_time_when_task_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='default_finish_date',
            field=models.IntegerField(blank=True, choices=[[0, 'today'], [1, 'tomorrow'], [2, 'next week'], [3, 'next month']], null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='default_type_finish_date',
            field=models.IntegerField(blank=True, choices=[[0, 'by'], [1, 'on']], default=1, null=True),
        ),
    ]
