# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-24 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationcontent_notificationrecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysummary',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notificationcontent',
            name='content',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='type',
            field=models.CharField(choices=[('email', 'email'), ('web', 'web')], db_index=True, default='email', max_length=50),
        ),
    ]
